#!/usr/bin/env sh

# Container
docker-compose down; docker-compose up & # --build omitted for speed

# Theme
(cd krypton; npx sass --watch assets/css/doku.scss assets/css/doku.css) &

# Visual Editor
(cd visual-editor; npx yarn watch ) &