#!/usr/bin/env sh
echo "Cloning repos"
git clone https://github.com/fablab-luenen/dokuwiki-preconfigured

# Krypton
rm -rf krypton
git clone https://github.com/fablab-luenen/dokuwiki-krypton krypton
(cd krypton; npx sass assets/css/doku.scss assets/css/doku.css)

# Visual Editor
# rm -rf visual-editor
# git clone https://github.com/fablab-luenen/dokuwiki-visual-editor visual-editor
# (cd visual-editor; npx yarn install && npx yarn build)

echo "All set up. To develop, use ./run"